cat_features: 
  - person_home_ownership
  - loan_intent
  - loan_grade
  - cb_person_default_on_file
num_features: 
  - person_age
  - person_income
  - person_emp_length
  - loan_amnt
  - loan_int_rate
  - loan_percent_income
  - cb_person_cred_hist_length
selected_features: 
  - person_home_ownership
  - loan_intent
  - loan_grade
  - cb_person_default_on_file
  - person_age
  - person_income
  - person_emp_length
  - loan_amnt
  - loan_int_rate
  - loan_percent_income
  - cb_person_cred_hist_length