name: lightgbm

params:
  boosting_type: gbdt
  objective: binary
  metric: auc
  learning_rate: 0.05
  num_leaves: 31
  lambda_l1: 0.4
  lambda_l2: 0.6
  num_threads: -1

path: res/models/
results: lightgbm_model.txt
early_stopping_rounds: 100
num_boost_round: 10000
verbose_eval: 100
seed: 42