defaults:
  - _self_
  - data: dataset
  - models: lightgbm
  - store: features
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  run:
    dir: .
  output_subdir: null

output:
  path: output
  submission: sample_submission.csv
  name: 5fold-baseline-lightgbm.csv
  
seed: 42